--Creacion tabla usuario
CREATE TABLE USUARIO(
    ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(100) NOT NULL,
    PRIMARY KEY(ID_USUARIO)
);

--Creacion tabla equipo
CREATE TABLE EQUIPO(
  ID_EQUIPO NUMBER(10) GENERATED ALWAYS AS IDENTITY,
  NOMBRE VARCHAR2(100) NOT NULL,
  PRIMARY KEY(ID_EQUIPO)
);

--Creacion tabla tareas
CREATE TABLE TARE(
    ID_TAREA NUMBER(10) GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    CREADOR_ID NUMBER(10) NOT NULL,
    FOREIGN KEY(CREADOR_ID) REFERENCES USUARIO(ID_USUARIO)
);

--Relacion entre usuario y equipo
CREATE TABLE USUARIO_EQUIPO(
    ID_USUARIO NUMBER(10), 
    ID_EQUIPO NUMBER(10),
    PRIMARY KEY(ID_USUARIO, ID_EQUIPO),
    CONSTRAINT FK_IDUSUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_IDEQUIPO FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

--Relacion asignacion de tareas
CREATE TABLE ASIGNACION_TAREAS(
    ID_USUARIO NUMBER(10),
    ID_TAREA NUMBER(10),
    PRIMARY KEY(ID_USUARIO, ID_TAREA),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY(ID_TAREA) REFERENCES EQUIPO(ID_EQUIPO)
);

--Creacion tabla gestor
CREATE TABLE GESTOR(
    ID_USUARIO NUMBER(10) PRIMARY KEY,
    FOREIGN KEY(ID_USUARIO) REFERENCES GESTOR(ID_USUARIO)
);

ALTER TABLE TARE RENAME TO TAREA;
