--Insercion usuarios
INSERT INTO USUARIO(NOMBRE) VALUES ('Cristina');
INSERT INTO USUARIO(NOMBRE) VALUES ('Ahri');
INSERT INTO USUARIO(NOMBRE) VALUES ('Hada');
INSERT INTO USUARIO(NOMBRE) VALUES ('Nora');
INSERT INTO USUARIO(NOMBRE) VALUES ('Onix');
INSERT INTO USUARIO(NOMBRE) VALUES ('Yuna');
INSERT INTO USUARIO(NOMBRE) VALUES ('Ana');
INSERT INTO USUARIO(NOMBRE) VALUES ('Jose');
INSERT INTO USUARIO(NOMBRE) VALUES ('Samuel');
INSERT INTO USUARIO(NOMBRE) VALUES ('Paula');

--Insercion equipos
INSERT INTO EQUIPO(NOMBRE) VALUES('Desarrollo');
INSERT INTO EQUIPO(NOMBRE) VALUES('Marketing');
INSERT INTO EQUIPO(NOMBRE) VALUES('Ventas');
INSERT INTO EQUIPO(NOMBRE) VALUES('Soporte');
INSERT INTO EQUIPO(NOMBRE) VALUES('Recursos Humanos');
INSERT INTO EQUIPO(NOMBRE) VALUES('Finanzas');
INSERT INTO EQUIPO(NOMBRE) VALUES('Legal');
INSERT INTO EQUIPO(NOMBRE) VALUES('Produccion');
INSERT INTO EQUIPO(NOMBRE) VALUES('I+D');
INSERT INTO EQUIPO(NOMBRE) VALUES('Logistica');

--Insercion tareas
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Desarrollar API', 1);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Diseñar UI', 2);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Campaña Publicitaria', 3);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Atencion Cliente', 4);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Contratar Personal', 5);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Analizar estados financieros', 6);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Revisar conrato', 7);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Control de calidad', 8);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Investigacion sobre IA', 9);
INSERT INTO TAREA(DESCRIPCION, ID_TAREA) VALUES('Optimizar logistica', 10);

