--Inserts Angel

--Insert en la tabla Usuario
INSERT INTO USUARIO (ID_USUARIO, NOMBRE) VALUES (3, 'Angel');
INSERT INTO USUARIO (ID_USUARIO, NOMBRE) VALUES (4, 'Javier');


--Insert en la tabla Equipo
INSERT INTO EQUIPO (ID_EQUIPO, NOMBRE) VALUES (3, 'Pruebas');
INSERT INTO EQUIPO (ID_EQUIPO, NOMBRE) VALUES (4, 'Gesti�n');

--Insert en la tabla Usuario_Equipo
INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO) VALUES (3, 4);
INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO) VALUES (4,3);

--Insert en la tabla Tarea
INSERT INTO TAREA (ID_TAREA, DESCRIPCION, CREADOR_ID) VALUES (2, 'Dise�ar interfaz', 2);
INSERT INTO TAREA (ID_TAREA, DESCRIPCION, CREADOR_ID) VALUES (3, 'Dise�ar base de datos', 3);

--Insert en la tabla Asignacion_Tareas
INSERT INTO ASIGNACION_TAREAS (ID_USUARIO, ID_TAREA) VALUES (3, 2);
INSERT INTO ASIGNACION_TAREAS (ID_USUARIO, ID_TAREA) VALUES (4, 3);

--Insert en la tabla Gestor
INSERT INTO GESTOR (ID_USUARIO) VALUES (2);
INSERT INTO GESTOR (ID_USUARIO) VALUES (3);