-- Inserts en la tabla USUARIO
INSERT INTO USUARIO (NOMBRE) VALUES ('Carlos López');
INSERT INTO USUARIO (NOMBRE) VALUES ('Elena Martínez');

-- Inserts en la tabla EQUIPO
INSERT INTO EQUIPO (NOMBRE) VALUES ('Desarrollo Web');
INSERT INTO EQUIPO (NOMBRE) VALUES ('Soporte Técnico');

-- Inserts en la tabla TAREA
INSERT INTO TAREA (DESCRIPCION, CREADOR_ID) VALUES ('Optimizar consultas SQL', 1);
INSERT INTO TAREA (DESCRIPCION, CREADOR_ID) VALUES ('Revisar documentación API', 2);

-- Inserts en la tabla USUARIO_EQUIPO
INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO) VALUES (1, 2);
INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO) VALUES (2, 1);

-- Inserts en la tabla ASIGNACION_TAREAS
INSERT INTO ASIGNACION_TAREAS (ID_USUARIO, ID_TAREA) VALUES (1, 1);
INSERT INTO ASIGNACION_TAREAS (ID_USUARIO, ID_TAREA) VALUES (2, 2);

-- Inserts en la tabla GESTOR
INSERT INTO GESTOR (ID_USUARIO) VALUES (1);
INSERT INTO GESTOR (ID_USUARIO) VALUES (2);