--Consulta Cristina: obtener usuarios con sus tareas y el equipo al que pertenecen
SELECT U.ID_USUARIO, U.NOMBRE AS USUARIO, T.ID_TAREA, T.DESCRIPCION AS TAREA, E.NOMBRE AS EQUIPO
FROM USUARIO U
JOIN ASIGNACION_TAREAS A ON U.ID_USUARIO = A.ID_USUARIO
JOIN TAREA T ON A.ID_TAREA = T.ID_TAREA
JOIN USUARIO_EQUIPO UE ON U.ID_USUARIO = UE.ID_USUARIO
JOIN EQUIPO E ON UE.ID_EQUIPO = E.ID_EQUIPO
ORDER BY E.NOMBRE, U.NOMBRE;
