








INSERT INTO USUARIO (NOMBRE) VALUES ('Antonio García');
INSERT INTO USUARIO (NOMBRE) VALUES ('María Sanchez');


INSERT INTO EQUIPO (NOMBRE) VALUES ('Equipo dax');
INSERT INTO EQUIPO (NOMBRE) VALUES ('Equipo rex');


INSERT INTO TAREA (DESCRIPCION, CREADOR_ID) VALUES ('Desarrollar módulo de login', 1);
INSERT INTO TAREA (DESCRIPCION, CREADOR_ID) VALUES ('Diseñar interfaz de usuario', 2);


INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO) VALUES (1, 1);
INSERT INTO USUARIO_EQUIPO (ID_USUARIO, ID_EQUIPO) VALUES (2, 2);



INSERT INTO ASIGNACION_TAREAS (ID_USUARIO, ID_TAREA) VALUES (1, 1);
INSERT INTO ASIGNACION_TAREAS (ID_USUARIO, ID_TAREA) VALUES (2, 2);


INSERT INTO GESTOR (ID_USUARIO) VALUES (1);
INSERT INTO GESTOR (ID_USUARIO) VALUES (2);




